Design apple home page
edemagbenyo/apple-website pull request #1
Opened 2019-09-30 17:59 UTC by edemagbenyo

Things learnt:
Position with flex and float
Backgroung: Image and gradient

2019-09-30 19:45 UTC, wathigo requested changes
### Great work @edemagbenyo  :clap: 
## The clone looks great!
**Please address the requirement below :point_down:  and submit another request for review**
_Happy Coding :)_

2019-09-30 19:45 UTC, wathigo commented on index.html
> +            <div><img src="./assets/img/1.jpg" alt=""></div>
**[REQUIRED]** This images should be links to the articles or `"#"`. Please change the parent of the `image` element from `div` to `img`

2019-09-30 21:06 UTC, Redvanisation requested changes
### Hello @edemagbenyo   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. Please style the four bottom elements beneath the background picture just like on the original website.

2. Please consider my comments below.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-09-30 21:06 UTC, Redvanisation commented on index.html
> +        </header>
The `<header>` tag shouldn't be inside the `<main>` tag

2019-09-30 21:06 UTC, Redvanisation commented on index.html
> +                </ul>
All of the `<li>` tags in the navigation should be links

2019-09-30 21:46 UTC, Redvanisation requested changes
### Hello @edemagbenyo 

**Well done implementing the changes requested, however the project doesn't look like it is required yet, please implement the changes below ⬇️**

- The page is still not looking like the original website, please fix the background to make it look exactly like the original apple page.

This is how it is looking on my screen: 

<img width="1671" alt="Screen Shot 2019-09-30 at 5 41 13 PM" src="https://user-images.githubusercontent.com/33462180/65919380-1c48f680-e3aa-11e9-91bf-999864f4621a.png">


### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-09-30 21:49 UTC, edemagbenyo commented
We are probably looking at different copy of the same website. Kindly give me a link to your copy. This is what i am looking at https://web.archive.org/web/20140301004610/http://www.apple.com/.

2019-10-01 07:24 UTC, bolah2009 approved these changes
## It's a :+1: from me

### [The clone](https://rawcdn.githack.com/edemagbenyo/apple-website/a433150ed2ecf2b78ee789a03e9925f94a47d8ae/index.html) uses CSS Backgrounds and griendeit effectively.

I would, however, suggest that the page to be longer (in height) than it is: Compare source page and the clone

|[Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/) (Preffered) | [Clone](https://rawcdn.githack.com/edemagbenyo/apple-website/a433150ed2ecf2b78ee789a03e9925f94a47d8ae/index.html) (Current)|
|:-----:|:-----:|
| ![Apple Source Page](https://user-images.githubusercontent.com/36057474/63733852-eb891500-c871-11e9-9989-2de9092b3fc5.png)  | ![image](https://user-images.githubusercontent.com/36057474/65942078-6d95cc00-e424-11e9-8bfa-809c73e9f3cf.png)  |

#### :heavy_check_mark: This project is approved :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-01 07:24 UTC, bolah2009 commented on assets/css/style.css
> +  border-left: 1px solid #fff;
Why are we using white border left here? :thinking: Also, we could add hover effects as in the [Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/).

![preffered apple nav hover](https://user-images.githubusercontent.com/36057474/62406543-8cebb680-b5a5-11e9-90c7-d795f787c77e.gif)

2019-10-01 07:39 UTC, merged